version: '3.8'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/todochat?schema=public'
      JWT_SECRET: 'your-secret-key-here'
      PORT: 4000
      EMAIL_HOST: 'smtp.gmail.com'
      EMAIL_PORT: 587
      EMAIL_SECURE: 'false'
      EMAIL_USER: 'assoftuz@gmail.com'
      EMAIL_PASSWORD: 'goje kwnw xvdm qhug'
      EMAIL_FROM: 'Todo Chat App <assoftuz@gmail.com>'
    dns:
      - 8.8.8.8  # Google DNS
      - 8.8.4.4  # Google DNS backup
    command: >
      sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todochat
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 